/**
 * The painted attacks: six mage ultimates and three boss swings.
 *
 * Sheets live at `src/assets/fx/<id>-sheet.webp` and are cut by
 * tools/pack-spells.mjs off clips generated by tools/gen-spells.mjs. Read those
 * two headers for how the art is made; this file is only the other end of the
 * contract, and there are three clauses to it.
 *
 * **The grid never varies.** Ten frames, five to a row, every cell the same
 * square, for every id. The packer enforces it so that this module can hardcode
 * it, the same way art/fire.js hardcodes the grid of the one sheet that was cut
 * off a still. That is also why `fire` is skipped below: its cell is 399x258 and
 * nothing about it matches these. Ricklow still throws a sheet from here — it is
 * called `flame` and it is one of the build's flipbooks, on this grid like the
 * rest — and `fire` stays what it always was, his fallback.
 *
 * **No alpha, so every frame is drawn with the `add` blend.** The clips are
 * generated on black and the packer clamps what is left of that black to zero,
 * so the backdrop adds nothing and the effect keeps exactly the light it had.
 * Drawn normally, every one of these arrives as a glow in a black box.
 *
 * **Frames 0..4 are the bolt in flight, 5..9 are it landing.** Same split as the
 * fire sheet, so `Vfx.spell` can drive both with one player. A boss sheet has no
 * flight half — nothing throws it — and simply gets played straight through.
 *
 * ## Why a glob and not eight imports
 *
 * A missing import is a build failure, and these sheets arrive one at a time:
 * the clips are generated per id, and a run that gets throttled halfway leaves
 * some of them on disk and some not. `import.meta.glob` resolves whatever is
 * actually there when Vite builds, so a half-finished set builds and ships, the
 * ids that made it play painted and the ids that did not fall back to the beam
 * they have always thrown. Nothing has to be commented out and back in.
 */

import { Rectangle, Texture } from "pixi.js";
import { canvasTexture } from "./textures.js";
import { paced } from "../core/idle.js";
import { FIRE, WATER, NATURE, LIGHTNING, ARCANE, WIND } from "../config.js";

/** The grid, exactly as tools/pack-spells.mjs packs it. */
const SHEET = { cols: 5, cell: 228, count: 10 };

/** Where the bolt stops travelling and the blast begins. */
export const SPELL_TRAVEL_LAST = 4;

/** Cells are square, which is the only shape the game needs from a sheet. */
export const SPELL_ASPECT = 1;

/**
 * Which sheet each mage throws.
 *
 * Ricklow's is `flame` and not `fire`, and the odd name is load-bearing. `fire`
 * is the painted comet in art/fire.js: cut off a still, on a 399x258 cell, with
 * a lead angle to correct for, and it is skipped by the glob above precisely
 * because nothing on this grid can play it. Giving the build's flipbook its own
 * id keeps both on disk, so `Vfx.spell` can prefer this one and still fall back
 * to the comet when the sheet is not there.
 */
export const SPELL_BY_ELEMENT = {
  [FIRE]: "flame",
  [WATER]: "water",
  [NATURE]: "nature",
  [LIGHTNING]: "lightning",
  [ARCANE]: "arcane",
  [WIND]: "wind",
};

/** The boss's three, by the name its attack rotation already uses. */
export const BOSS_SPELLS = { breath: "breath", smash: "slam", rake: "claw" };

/**
 * Whatever sheets Vite found at build time, as id -> inlined data URI.
 *
 * `assetsInlineLimit` is set high enough in vite.config.js that these come back
 * as base64 rather than URLs, which is the whole point: the deliverable is one
 * self-contained file that makes no requests.
 *
 * `fire-sheet.webp` is excluded in the *pattern* and not only in the loop below,
 * and that is worth 62 kB of the deliverable. `eager: true` is a build-time
 * instruction: every path the glob matches is imported and, at this inline
 * limit, base64'd into the bundle whether or not anything reads it back. The
 * sheet is also imported directly by art/fire.js — on its own grid, off a still
 * — so skipping it at runtime left the file inlined twice over, once here and
 * once there, for 125 kB of bundle spent on 62 kB of art. A negative pattern is
 * how a glob is told not to reach something; a `continue` is only how the
 * program is told not to use it.
 */
const FOUND = import.meta.glob(
  ["../assets/fx/*-sheet.webp", "!../assets/fx/fire-sheet.webp"],
  {
    eager: true,
    query: "?url",
    import: "default",
  },
);

const urls = {};
for (const path in FOUND) {
  const id = path.slice(path.lastIndexOf("/") + 1).replace("-sheet.webp", "");
  // Cut off a still, on its own grid, with its own module. Not one of these.
  // The glob above no longer matches it, so this is a guard rather than a
  // filter: it is what keeps the sheet out if that pattern is ever widened.
  if (id === "fire") continue;
  urls[id] = FOUND[path];
}

/** id -> ten textures. Only holds what actually decoded. */
const frames = {};
let loaded = false;

/**
 * Cut one sheet into its ten frames.
 *
 * Every frame is a window onto one texture rather than a texture of its own, so
 * swapping frames costs nothing at render time — the batch never breaks.
 */
async function cut(url) {
  const img = new Image();
  img.src = url;
  await img.decode();
  const c = document.createElement("canvas");
  c.width = img.width;
  c.height = img.height;
  c.getContext("2d").drawImage(img, 0, 0);
  const sheet = canvasTexture(c);

  const out = [];
  for (let i = 0; i < SHEET.count; i++) {
    out.push(
      new Texture({
        source: sheet.source,
        frame: new Rectangle(
          (i % SHEET.cols) * SHEET.cell,
          Math.floor(i / SHEET.cols) * SHEET.cell,
          SHEET.cell,
          SHEET.cell,
        ),
      }),
    );
  }
  return out;
}

/**
 * Decode every sheet that shipped — after the first frame, not before it.
 *
 * Never rejects, and one bad sheet never takes the others with it: an id that
 * fails to decode is simply absent from `spellFrames`, and the hero or the boss
 * swing that wanted it falls back to the effect it threw before. That fallback
 * is the normal case until the clips exist, not an error path.
 *
 * It is also what makes this safe to load late. Nine sheets is six megapixels,
 * a fifth of everything this creative decodes, and not one of them can be
 * wanted until a match is made — `Vfx.spell` asks for its frames at the moment
 * of the cast and takes null for an answer. So the queue below runs a sheet to
 * a frame once the fight is up, and a cast that beats it to the punch throws the
 * beam instead, exactly as it does for an id whose clip was never generated.
 * See the deferred pass in main.js and core/idle.js.
 */
export async function loadSpellArt() {
  if (loaded) return frames;
  loaded = true;
  await paced(
    Object.keys(urls).map((id) => async () => {
      frames[id] = await cut(urls[id]);
      // A throw is caught by `paced` and leaves the id out of `frames`, which
      // is exactly how the caller asks.
    }),
  );
  return frames;
}

/** The ten frames for one id, or null if that sheet never arrived. */
export function spellFrames(id) {
  return (id && frames[id]) || null;
}
