/**
 * The painted attacks: five mage ultimates and three boss swings.
 *
 * Sheets live at `src/assets/fx/<id>-sheet.webp` and are cut by
 * tools/pack-spells.mjs off clips generated by tools/gen-spells.mjs. Read those
 * two headers for how the art is made; this file is only the other end of the
 * contract, and there are three clauses to it.
 *
 * **The grid never varies.** Ten frames, five to a row, every cell the same
 * square, for every id. The packer enforces it so that this module can hardcode
 * it, the same way art/fire.js hardcodes the grid of the one sheet that was cut
 * off a still. That is also why fire is skipped below: its cell is 399x258 and
 * nothing about it matches these.
 *
 * **No alpha, so every frame is drawn with the `add` blend.** The clips are
 * generated on black and the packer clamps what is left of that black to zero,
 * so the backdrop adds nothing and the effect keeps exactly the light it had.
 * Drawn normally, every one of these arrives as a glow in a black box.
 *
 * **Frames 0..4 are the bolt in flight, 5..9 are it landing.** Same split as the
 * fire sheet, so `Vfx.spell` can drive both with one player. A boss sheet has no
 * flight half — nothing throws it — and simply gets played straight through.
 *
 * ## Why a glob and not eight imports
 *
 * A missing import is a build failure, and these sheets arrive one at a time:
 * the clips are generated per id, and a run that gets throttled halfway leaves
 * some of them on disk and some not. `import.meta.glob` resolves whatever is
 * actually there when Vite builds, so a half-finished set builds and ships, the
 * ids that made it play painted and the ids that did not fall back to the beam
 * they have always thrown. Nothing has to be commented out and back in.
 */

import { Rectangle, Texture } from "pixi.js";
import { canvasTexture } from "./textures.js";
import { WATER, NATURE, LIGHTNING, ARCANE, WIND } from "../config.js";

/** The grid, exactly as tools/pack-spells.mjs packs it. */
const SHEET = { cols: 5, cell: 228, count: 10 };

/** Where the bolt stops travelling and the blast begins. */
export const SPELL_TRAVEL_LAST = 4;

/** Cells are square, which is the only shape the game needs from a sheet. */
export const SPELL_ASPECT = 1;

/**
 * Which sheet each mage throws.
 *
 * Fire is deliberately absent: Ricklow's ultimate was painted off a still long
 * before any of this and keeps its own module, its own grid and its own lead
 * angle. `Vfx.spell` sends him to `Vfx.fireball` instead.
 */
export const SPELL_BY_ELEMENT = {
  [WATER]: "water",
  [NATURE]: "nature",
  [LIGHTNING]: "lightning",
  [ARCANE]: "arcane",
  [WIND]: "wind",
};

/** The boss's three, by the name its attack rotation already uses. */
export const BOSS_SPELLS = { breath: "breath", smash: "slam", rake: "claw" };

/**
 * Whatever sheets Vite found at build time, as id -> inlined data URI.
 *
 * `assetsInlineLimit` is set high enough in vite.config.js that these come back
 * as base64 rather than URLs, which is the whole point: the deliverable is one
 * self-contained file that makes no requests.
 */
const FOUND = import.meta.glob("../assets/fx/*-sheet.webp", {
  eager: true,
  query: "?url",
  import: "default",
});

const urls = {};
for (const path in FOUND) {
  const id = path.slice(path.lastIndexOf("/") + 1).replace("-sheet.webp", "");
  // Cut off a still, on its own grid, with its own module. Not one of these.
  if (id === "fire") continue;
  urls[id] = FOUND[path];
}

/** id -> ten textures. Only holds what actually decoded. */
const frames = {};
let loaded = false;

/**
 * Cut one sheet into its ten frames.
 *
 * Every frame is a window onto one texture rather than a texture of its own, so
 * swapping frames costs nothing at render time — the batch never breaks.
 */
async function cut(url) {
  const img = new Image();
  img.src = url;
  await img.decode();
  const c = document.createElement("canvas");
  c.width = img.width;
  c.height = img.height;
  c.getContext("2d").drawImage(img, 0, 0);
  const sheet = canvasTexture(c);

  const out = [];
  for (let i = 0; i < SHEET.count; i++) {
    out.push(
      new Texture({
        source: sheet.source,
        frame: new Rectangle(
          (i % SHEET.cols) * SHEET.cell,
          Math.floor(i / SHEET.cols) * SHEET.cell,
          SHEET.cell,
          SHEET.cell,
        ),
      }),
    );
  }
  return out;
}

/**
 * Decode every sheet that shipped, before the first frame.
 *
 * Never rejects, and one bad sheet never takes the others with it: an id that
 * fails to decode is simply absent from `spellFrames`, and the hero or the boss
 * swing that wanted it falls back to the effect it threw before. That fallback
 * is the normal case until the clips exist, not an error path.
 */
export async function loadSpellArt() {
  if (loaded) return frames;
  loaded = true;
  await Promise.all(
    Object.keys(urls).map(async (id) => {
      try {
        frames[id] = await cut(urls[id]);
      } catch {
        // Left out of `frames`, which is exactly how the caller asks.
      }
    }),
  );
  return frames;
}

/** The ten frames for one id, or null if that sheet never arrived. */
export function spellFrames(id) {
  return (id && frames[id]) || null;
}
